Laba4.5/Laba4.5/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba4._5.Managers;
using Laba4._5.Managers.Hotels;
using Laba4._5.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkId=397860

namespace Laba4._5.Controllers
{
    public class HotelController : Controller
    {
        private readonly IHotelsManager _manager ;

        public HotelController(IHotelsManager manager)
        {
            _manager = manager;
        }
        public async Task<ViewResult> ShowHotel()
        {
            var entity = await _manager.GetAll();
            return View(entity);

        }
       

        public ViewResult CreateHotel()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateOrUpdateHotels request)
        { 
            await _manager.AddHotel(request);
            return RedirectToAction(nameof(ShowHotel));
        }
        public async Task<ViewResult> EditHotel(Guid Id)
        {
            var entity = await _manager.GetById(Id);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Guid HotelId, CreateOrUpdateHotels request)
        {
            await _manager.EditHotel(HotelId, request);
            return RedirectToAction(nameof(ShowHotel));
        }
        public async Task<ActionResult> Kick(Hotel entity)
        {
            await _manager.Delete(entity);
            return RedirectToAction(nameof(ShowHotel));
        }
        public async Task<ViewResult> ShowAllHotel()
        {
            var entity = await _manager.GetAll();
            return View(entity);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Laba4.5/Laba4.5/Views/Hotel/CreateHotel.cshtml
@model Laba4._5.Managers.Hotels.CreateOrUpdateHotels

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth" />
    <title></title>
</head>
<body>
    @using (Html.BeginForm("Create", "Hotel", FormMethod.Post))
    {
        <label>Название отеля</label>
        <input Id="name" type="text" name="name" /> <br />
        <label>Количество этажей в отеле:</label>
        <input Id="floors" type="text" name="floors" /> <br />
        <label>Количестов номеров:</label>
        <input Id="KolNum" type="text" name="KolNum" /> <br />
        <label>Количестов сотрудников:</label>
        <input Id="kolsot" type="text" name="kolsot" /> <br />

        <input type="submit" value="Добавить новый отель" /><br /><br />
    }
    <div>
        <a href="/Hotel/ShowHotels">Вернуться к списку отеля</a><br /><br />
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Hotel/EditHotel.cshtml
@model Laba4._5.Storage.Entity.Hotel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth"/>
    <title></title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Edit", "Hotel", FormMethod.Post))
        {
            <input Id="HotelId" name="HotelId" type="hIdden" value="@Model.Id" />
            <label>Название отеля:</label>
            <input Id="name" type="text" name="name" value="@Model.name" /> <br />
            <label>Количество этажей в отеле:</label>
            <input Id="floors" type="text" name="floors" value="@Model.floors." /> <br />
            <label>Количестов номеров:</label>
            <input Id="KolNum" type="text" name="KolNum" value="@Model.KolNum" /> <br />
            <label>Количестов сотрудников:</label>
            <input Id="kolsot" type="text" name="kolsot" value="@Model.kolsot" /> <br />
            <input type="submit" value="Редактировать отель" /><br /><br />
        }
        <div>
            <a href="/Hotel/ShowHotels">Вернутся к списку отелей</a><br /><br />
        </div>
     </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Hotel/ShowHotel.cshtml
@model IEnumerable<Laba4._5.Storage.Entity.Hotel>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>Show Hotels</title>
</head>
<body>
    <h1>Отели</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Название отеля</th>
            <th>Количество этажей в отеле</th>
            <th>Количестов номеров</th>
            <th>Количестов сотрудников</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        @{
            foreach(var item in Model)
            {
                <tr>
                    <td>@item.name</td>
                    <td>@item.floors</td>
                    <td>@item.KolNum.</td>
                    <td>@item.kolsot</td>
                    <td><a href="/Hotel/EditHotel/@item.Id">Редактировать</a> </td>
                    <td><a href="/Hotel/Kick/@item.Id">Удалить</a></td>
                    <td><a href="/Personal/ShowPersonals/@item.Id">Персонал</a></td>
                    <td><a href="/CHnumber/ShowCHnumber/@item.Id">Номера</a></td>

                </tr>
            }
        }

        </table>
    @using (Html.BeginForm("CreateHotel","Hotel"))
    {
        <div>
            <input type="submit" value="Добавить новый отель"/>
        </div>
    }
</body>
</html>