Laba4.5/Laba4.5/Controllers/CHnumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba4._5.Managers;
using Laba4._5.Managers.CHnumbers;
using Laba4._5.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkId=397860

namespace Laba4._5.Controllers
{
    public class CHnumberController : Controller
    {
        private readonly ICHnumbersManager _manager;

        public CHnumberController(ICHnumbersManager manager)
        {
            _manager = manager;
        }
        public async Task<ViewResult> ShowCHnumber(Guid Id)
        {
            Perenos perenos = new Perenos();
            Perenos.chnumbers = (List<CHnumber>)await _manager.GetAll();
            Perenos.Guid = Id;
            return View(perenos);

        }
        public async Task<ViewResult> AfterShowCHnumber()
        {
            Perenos perenos = new Perenos();
            Perenos.chnumbers = (List<CHnumber>)await _manager.GetAll();
            return View(perenos);
        }

        public ViewResult CreateCHnumber()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateOrUpdateCHnumbers request)
        {
            request.HotelId = Perenos.Guid;
            await _manager.AddCHnumber(request);
            return RedirectToAction(nameof(AfterShowCHnumber));
        }
        public async Task<ViewResult> EditCHnumber(Guid Id)
        {
            var entity = await _manager.GetById(Id);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Guid CHnumberId, CreateOrUpdateCHnumbers request)
        {
            await _manager.EditCHnumber(CHnumberId, request);
            return RedirectToAction(nameof(AfterShowCHnumber));
        }
        public async Task<ActionResult> Kick(CHnumber entity)
        {
            await _manager.Delete(entity);
            return RedirectToAction(nameof(AfterShowCHnumber));
        }
        public async Task<ViewResult> ShowAllCHnumbers()
        {
            Perenos perenos = new Perenos();
            Perenos.chnumbers = (List<CHnumber>)await _manager.GetAll();
            return View(perenos);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Laba4.5/Laba4.5/Views/CHnumber/AfterShowCHnumber.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <<meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />   
</head>
<body>
    <h1>Характеристика номеров</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Количество комнат</th>
            <th>Количество спальных мест</th>
            <th></th>
            <th></th>
            <th></th>
           
        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.chnumbers)
            {
                @if(item.HotelId == Laba4._5.Managers.Perenos.Guid)
                {
    <tr>
        <td>@item.rooms</td>
        <td>@item.sleep</td>
        <td><a href="/CHnumber/EditCHnumber/@item.Id"> "Редактировать"</a></td>

        <td><a href="/CHnumber/Kick/@item.Id">Удалить </a></td>
        <td><a href="/Number/ShowNumbers/@item.Id"> Номера</a></td>
    </tr>
                }
            }
        }
    </table>
    @using(Html.BeginForm("CreateCHnumber","CHnumber"))
    {
        <div>
            <input type="submit" value="Добавить характеристику" />

        </div>
    }
    <div>
        <a href="/CHnumber/ShowAllCHnumbers">Показать всю характеристику</a>
    </div>
    <div>
        <a href ="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/CHnumber/CreateCHnumber.cshtml
@model Laba4._5.Managers.CHnumbers.CreateOrUpdateCHnumbers

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth" />
    <title></title>
</head>
<body>
    @using (Html.BeginForm("Create", "Chnumber", FormMethod.Post))
    {
        <label>Количество комнат</label>
        <input Id="rooms" type="text" name="rooms" /> <br />
        <label>Количество спальных мест:</label>
        <input Id="sleep" type="text" name="sleep" /> <br />
        

        <input type="submit" value="Добавить новую характеристику" /><br /><br />
    }
    <div>
        <a href="/Chnumber/ShowCHnumber">Вернуться к списку характеристики</a><br /><br />
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/CHnumber/EditCHnumber.cshtml
@model Laba4._5.Storage.Entity.CHnumber
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth" />
    <title></title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Edit", "Chnumber", FormMethod.Post))
        {
            <input Id="CHnumberId" name="ChnumberId" type="hIdden" value="@Model.Id" />
            <label>Количество комнат:</label>
            <input Id="rooms" type="text" name="rooms" value="@Model.rooms" /> <br />
            <label>Количество спальных мест:</label>
            <input Id="sleep" type="text" name="sleep" value="@Model.sleep." /> <br />
            <input type="submit" value="Редактировать характеристику" /><br /><br />
        }
        <div>
            <a href="/CHnumber/ShowCHnumber">Вернутся к списку характеристик</a><br /><br />
        </div>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/CHnumber/ShowAllCHnumbers.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />
</head>
<body>
    <h1>Характеристика номеров</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Количество комнат</th>
            <th>Количество спальных мест</th>
            <th></th>
            <th></th>
            <th></th>

        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.chnumbers)
            {
                
                    <tr>
                        <td>@item.rooms</td>
                        <td>@item.sleep</td>
                        <td><a href="/CHnumber/EditCHnumber/@item.Id"> "Редактировать"</a></td>

                        <td><a href="/CHnumber/Kick/@item.Id">Удалить </a></td>
                        <td><a href="/Number/ShowNumbers/@item.Id"> Номера</a></td>
                    </tr>
                
            }
        }
    </table>
    @using (Html.BeginForm("Create", "CHnumber"))
    {
        <div>
            <input type="submit" value="Добавить характеристику" />

        </div>
    }
    <div>
        <a href="/CHnumber/ShowAllCHnumbers">Показать всю характеристику</a>
    </div>
    <div>
        <a href="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/CHnumber/ShowCHnumber.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />
</head>
<body>
    <h1>Характеристика номеров</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Количество комнат</th>
            <th>Количество спальных мест</th>
            <th></th>
            <th></th>
            <th></th>

        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.chnumbers)
            {
                @if (item.HotelId == Laba4._5.Managers.Perenos.Guid)
                {
                    <tr>
                        <td>@item.rooms</td>
                        <td>@item.sleep</td>
                        <td><a href="/CHnumber/EditCHnumber/@item.Id"> "Редактировать"</a></td>

                        <td><a href="/CHnumber/Kick/@item.Id">Удалить </a></td>
                        <td><a href="/Number/ShowNumbers/@item.Id"> Номера</a></td>
                    </tr>
                }
            }
        }
    </table>
    @using (Html.BeginForm("CreateCHnumber", "CHnumber"))
    {
        <div>
            <input type="submit" value="Добавить характеристику" />

        </div>
    }
    <div>
        <a href="/CHnumber/ShowAllCHnumbers">Показать всю характеристику</a>
    </div>
    <div>
        <a href="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>