Laba4.5/Laba4.5/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Laba4._5.Managers;
using Laba4._5.Managers.Personals;
using Laba4._5.Storage.Entity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkId=397860

namespace Laba4._5.Controllers
{
    public class PersonalController : Controller
    {
        private readonly IPersonalsManager _manager;

        public PersonalController(IPersonalsManager manager)
        {
            _manager = manager;
        }

        [HttpGet]

        public async Task<ViewResult> ShowPersonals(Guid Id)
        {
            Perenos perenos = new Perenos();
            Perenos.Guid = Id;
            Perenos.personals = (List<Personal>)await _manager.GetAll();
            return View(perenos);
        }
        public async Task<ViewResult> AfterShowPersonals()
        {
            Perenos perenos = new Perenos();
            Perenos.personals= (List<Personal>)await _manager.GetAll();
            return View(perenos);
        }
        public ViewResult CreatePersonal()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateOrUpdatePersonals request)
        {
            request.HotelId = Perenos.Guid;
            await _manager.AddPersonal(request);
            return RedirectToAction(nameof(AfterShowPersonals));
        }
        public async Task<ViewResult>  EditPersonal(Guid Id)
        {
            var entity = await _manager.GetById(Id);
            return View(entity);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Guid PersonalId, CreateOrUpdatePersonals request)
        {
            await _manager.EditPersonal(PersonalId, request);
            return RedirectToAction(nameof(AfterShowPersonals));
        }

        public async Task<ActionResult> Kick(Personal entity)
        {
            await _manager.Delete(entity);
            return RedirectToAction(nameof(AfterShowPersonals));
        }

        public async Task<ViewResult> ShowAllPersonals()
        {
            Perenos perenos = new Perenos();
            Perenos.personals = (List<Personal>)await _manager.GetAll();
            return View(perenos);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Laba4.5/Laba4.5/Views/Personal/AfterShowPersonals.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />
</head>
<body>
    <h1>Персонал</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Должность</th>
            <th></th>
            <th></th>
            
        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.personals)
            {
                @if (item.HotelId == Laba4._5.Managers.Perenos.Guid)
                {
                    <tr>
                        <td>@item.name</td>
                        <td>@item.lastname</td>
                        <td>@item.dolzhnost</td>
                        <td><a href="/Personal/EditPersonal/@item.Id"> "Редактировать"</a></td>                       
                        <td><a href="/Personal/kick/@item.Id">"Удалить" </a></td>
                    </tr>
                }
            }
        }
    </table>
    @using (Html.BeginForm("CreatePersonal", "Personal"))
    {
        <div>
            <input type="submit" value="Добавить персонал" />

        </div>
    }
    <div>
        <a href="/Personal/ShowAllPersonals">Показать весь персонал</a>
    </div>
    <div>
        <a href="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Personal/CreatePersonal.cshtml
@model Laba4._5.Managers.Personals.CreateOrUpdatePersonals

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth" />
    <title></title>
</head>
<body>
    @using (Html.BeginForm("Create", "Personal", FormMethod.Post))
    {
        <label>Имя</label>
        <input Id="name" type="text" name="name" /> <br />
        <label>Фамилия:</label>
        <input Id="lastname" type="text" name="lastname" /> <br />
        <label>Должность</label>
        <input Id="dolzhnost" type="text" name="dolzhnost" /> <br />
        


        <input type="submit" value="Добавить ноый персонал" /><br /><br />
    }
    <div>
        <a href="/Personal/ShowPersonals">Вернуться к списку персонала</a><br /><br />
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Personal/EditPersonal.cshtml
@model Laba4._5.Storage.Entity.Personal
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" name="viewport" content="wIdth=device-wIdth" />
    <title></title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Edit", "Personal", FormMethod.Post))
        {
            <input Id="PersonalId" name="PersonalId" type="hIdden" value="@Model.Id" />
            <label>Имя:</label>
            <input Id="name" type="text" name="name" value="@Model.name" /> <br />
            <label>Фамилия:</label>
            <input Id="lastname" type="text" name="lastname" value="@Model.lastname." /> <br />
            <label>Должность:</label>
            <input Id="dolzhnost" type="text" name="dolzhnost" value="@Model.dolzhnost" /> <br />
  
            <input type="submit" value="Редактировать персонал" /><br /><br />
        }
        <div>
            <a href="/Personal/ShowPersonals">Вернутся к списку персонала</a><br /><br />
        </div>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Personal/ShowAllPersonals.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />
</head>
<body>
    <h1>Персонал</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Должность</th>
            <th></th>
            <th></th>

        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.personals)
            {
                
                    <tr>
                        <td>@item.name</td>
                        <td>@item.lastname</td>
                        <td>@item.dolzhnost</td>
                        <td><a href="/Personal/EditPersonal/@item.Id"> "Редактировать"</a></td>
                        <td><a href="/Personal/kick/@item.Id">"Удалить" </a></td>
                    </tr>
                
            }
        }
    </table>
    @using (Html.BeginForm("CreatePersonal", "Personal"))
    {
        <div>
            <input type="submit" value="Добавить персонал" />

        </div>
    }
    <div>
        <a href="/Personal/ShowAllPersonals">Показать весь персонал</a>
    </div>
    <div>
        <a href="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>

Laba4.5/Laba4.5/Views/Personal/ShowPersonals.cshtml
@model Laba4._5.Managers.Perenos

@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <
    <meta name="viewport" content="wIdth=device-wIdth" />
    <title>ShowCHnumber</title> />
</head>
<body>
    <h1>Персонал</h1>
    <table border="1" wIdth="100%" cellpadding="5">
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Должность</th>
            <th></th>
            <th></th>

        </tr>
        @{
            foreach (var item in Laba4._5.Managers.Perenos.personals)
            {
                @if (item.HotelId == Laba4._5.Managers.Perenos.Guid)
                {
                    <tr>
                        <td>@item.name</td>
                        <td>@item.lastname</td>
                        <td>@item.dolzhnost</td>
                        <td><a href="/Personal/EditPersonal/@item.Id"> "Редактировать"</a></td>
                        <td><a href="/Personal/kick/@item.Id">"Удалить" </a></td>
                    </tr>
                }
            }
        }
    </table>
    @using (Html.BeginForm("CreatePersonal", "Personal"))
    {
        <div>
            <input type="submit" value="Добавить персонал" />

        </div>
    }
    <div>
        <a href="/Personal/ShowAllPersonals">Показать весь персонал</a>
    </div>
    <div>
        <a href="/Hotel/ShowHotel">Вернутся к списку Отелей</a>
    </div>
</body>
</html>